Makefile.in: add silent rules (+ refactoring).

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,102 +1,121 @@
-# Source file directory:
-SRC_DIR=@srcdir@/src
+# Source file root directory:
+srcdir:= @srcdir@
 
-# Build directories:
-DEP_DIR=deps
-OBJ_DIR=objs
-MOD_DIR=mods
-LIB_DIR=lib
-BIN_DIR=bin
+# Source file subdirectories:
+subdirs:= src
 
-# Install directories:
-prefix=@prefix@
-exec_prefix=@exec_prefix@
+# Installation directories:
+prefix:= @prefix@
+exec_prefix:= @exec_prefix@
 
-# Compilers, building tools and the corresponding flags:
-FC=@FC@
-FCFLAGS=@FC_MOD_IN@$(MOD_DIR) -I$(SRC_DIR)/include @FC_MOD_OUT@$(MOD_DIR) @FCFLAGS@
-LDFLAGS=@LDFLAGS@
-LIBS=@LIBS@
+# Fortran module file directory:
+moddir:= mod
 
-AR=@AR@
-INSTALL=@INSTALL@
+# Compilers and flags:
+FC= @FC@
+FCFLAGS= @FCFLAGS@
+LDFLAGS= @LDFLAGS@
+LIBS= @LIBS@
+config_FCFLAGS:= @FC_MOD_IN@$(moddir) @FC_MOD_OUT@$(moddir) @FC_INC_FLAG@$(srcdir)/src/include @FC_INC_FLAG_PP_f90@$(srcdir)/src/include @NETCDF_FCFLAGS@ @config_FCFLAGS@
+config_LIBS:= @NETCDF_FCLIBS@
+
+# Other utilities:
+INSTALL= @INSTALL@
 INSTALL_DATA=@INSTALL_DATA@
+AR= @AR@
+PYTHON= @PYTHON@
+DEPLIST= $(PYTHON) $(srcdir)/mkhelper/deplist.py
+DEPGEN= $(PYTHON) $(srcdir)/mkhelper/depgen.py
 
-# Dependency generation command:
-DEPGEN=@PYTHON@ @srcdir@/mkhelper/depgen.py \
-       @depgen.config $< -o $@ -d $(@:.d=.debug) \
-       --obj-name $(OBJ_DIR)/$(<F:.f90=.o) --src-name $(<F)
+# Silent rule prefixes:
+V= @DEFAULT_VERBOSITY@
+ifeq ($(V), 0)
+silent_FCLD=   @echo "  FCLD    " $@;
+silent_FC=     @echo "  FC      " $@;
+silent_MKDIR=  @echo "  MKDIR   " $(@D);
+silent_DEPGEN= @echo "  DEPGEN  " $@;
+silent_AR=     @echo "  AR      " $@;
+endif
 
-# Dependency listing command:
-DEPLIST=@PYTHON@ @srcdir@/mkhelper/deplist.py
+# Source files:
+srcs:= $(shell find $(addprefix $(srcdir)/, $(subdirs)) -name '*.f90')
 
-# List of the dependency files:
-srcs=$(notdir $(shell find $(SRC_DIR) -name '*.f90'))
-DEP_FILES=$(addprefix $(DEP_DIR)/, $(srcs:.f90=.f90.d))
+# Stamp files of the build directories:
+dirstamps:= $(patsubst $(srcdir)/%, %.dirstamp, $(sort $(dir $(srcs)))) $(moddir)/.dirstamp
+
+# Dependency files:
+depfiles:= $(patsubst $(srcdir)/%, %.d, $(srcs))
+
+# Root object file:
+rootobj:= src/program/main.o
 
 # Source file selective search paths:
-vpath %.f90 $(shell find $(SRC_DIR) -type d)
+vpath %.f90 $(srcdir)
 
 # Disable built-in suffix rules:
 .SUFFIXES:
 # Targets not associated with files:
-.PHONY: all depend clean distclean maintainer-clean install
+.PHONY: all depend mostlyclean clean distclean maintainer-clean install
 # Keep sentinel files of created directories:
-.PRECIOUS: %/.sentinel
+.PRECIOUS: $(dirstamps)
 
 # User interface rules:
-all: $(BIN_DIR)/main;
+all: main
 
-depend: $(DEP_FILES)
+depend: $(depfiles)
 
-clean:
-	rm -rf $(DEP_DIR) $(OBJ_DIR) $(MOD_DIR) $(LIB_DIR) $(BIN_DIR)
+mostlyclean:
+	rm -f main libmain.a $(patsubst $(srcdir)/%.f90, %.o, $(srcs)) $(moddir)/*.@FC_MOD_FILE_EXT@
+
+clean: mostlyclean
+	rm -rf $(depfiles) $(depfiles:.d=.debug) $(dirstamps)
 
 distclean: clean
 	rm -f config.log config.status Makefile depgen.config
+	find -name '*.pyc' -delete -o -name '*.pyo' -delete -o -name '__pycache__' -delete
+	@for dir in $(subdirs) $(moddir) externals; do \
+	  if test -d "$$dir"; then \
+	    echo "find '$$dir' -type d -empty -delete"; \
+	    find "$$dir" -type d -empty -delete; \
+	  fi; \
+	done
 
 maintainer-clean: distclean
-	rm -rf @srcdir@/autom4te.cache $(shell find @srcdir@/mkhelper -name '*.pyc' -o -name '*.pyo' -o -name '__pycache__')
+	rm -rf autom4te.cache
 
-install: $(BIN_DIR)/main $(LIB_DIR)/libmain.a
-	$(INSTALL) -d @bindir@ @libdir@
-	$(INSTALL) $(BIN_DIR)/main @bindir@/main
-	$(INSTALL_DATA) $(LIB_DIR)/libmain.a @libdir@/libmain.a
+install: all
+	$(INSTALL) -d @bindir@ && $(INSTALL) main @bindir@/main
+	$(INSTALL) -d @libdir@ && $(INSTALL_DATA) libmain.a @libdir@/libmain.a
 
 # Main building rules:
-$(BIN_DIR)/main: $(OBJ_DIR)/main.o $(LIB_DIR)/libmain.a | $(BIN_DIR)/.sentinel
-	$(FC) $(FCFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)
+main: $(rootobj) libmain.a
+	$(silent_FCLD)$(FC) -o $@ $(config_FCFLAGS) $(FCFLAGS) $(LDFLAGS) $^ $(config_LIBS) $(LIBS)
 
-$(LIB_DIR)/libmain.a: $(shell $(DEPLIST) -p '*.o' -t $(OBJ_DIR)/main.o --inc-oo -f $(DEP_DIR)/*.d) | $(LIB_DIR)/.sentinel
-	rm -f $@ && $(AR) cru $@ $^
+libmain.a: $(shell $(DEPLIST) -t $(rootobj) -p '*.o' --inc-oo -f $(depfiles) Makefile)
+	$(silent_AR)rm -f $@ && $(AR) cru $@ $^
 
-$(OBJ_DIR)/%.o: %.f90 | $(MOD_DIR)/.sentinel $(OBJ_DIR)/.sentinel
-	$(FC) -c $(FCFLAGS) -o $@ @FCFLAGS_f90@ $<
+%.o: %.f90 | $(dirstamps)
+	$(silent_FC)$(FC) -o $@ -c $(config_FCFLAGS) $(FCFLAGS) @FCFLAGS_f90@ $<
 
-# Auxiliary building rules:
-$(MOD_DIR)/%.@FC_MODULE_EXT@:
+# Fortran module file tracking rule:
+$(moddir)/%.@FC_MOD_FILE_EXT@:
 	@if test -z $<; then \
-	  echo "Cannot find Fortran source file providing module '$(basename $(@F))'."; \
+	  echo "Cannot find Fortran source file providing module '$(basename $(@F))'." >&2; \
 	elif test ! -f $@; then \
 	  rm -f $<; $(MAKE) $<; \
 	fi
 
-# Some old versions of GNU Make strip the trailing slash when
-# searching for pattern rules, which is why we have to
-# create sentinel files inside the created directories:
-%/.sentinel:
-	@echo "Creating directory '$(@D)'..."; mkdir $(@D); touch $@
+# Directory generation rule:
+%/.dirstamp:
+	$(silent_MKDIR)@MKDIR_P@ $(@D) && touch $@
 
-# Common dependency generation rule:
-$(DEP_DIR)/%.f90.d: %.f90 | $(DEP_DIR)/.sentinel
-	$(DEPGEN) -- @DEPGEN_DEFS@ $(FCFLAGS)
+# Dependency generation rule:
+%.f90.d: %.f90 | $(dirstamps)
+	$(silent_DEPGEN)$(DEPGEN) @depgen.config -o $@ --obj-name $(@:.f90.d=.o) -d $(@:.d=.debug) $< -- @DEPGEN_DEFS@ $(config_FCFLAGS) $(FCFLAGS)
 
-# Undetectable dependencies:
-$(DEP_DIR)/main.f90.d: main.f90 | $(DEP_DIR)/.sentinel
-	$(DEPGEN) --oo-prereqs=$(OBJ_DIR)/implicit_external.o -- @DEPGEN_DEFS@ $(FCFLAGS)
+# Undetectable Fortran dependencies:
+src/program/main.o:| src/program/implicit_external.o
 
-$(DEP_FILES): Makefile
-
-ifeq (,$(filter $(MAKECMDGOALS), depend clean distclean maintainer-clean))
--include $(DEP_FILES)
+ifeq (,$(filter $(MAKECMDGOALS), depend mostlyclean clean distclean maintainer-clean))
+-include $(depfiles)
 endif
